#pragma once

#undef RGBLED_NUM
#define TAPPING_TOGGLE 2
#define RGBLED_NUM 12
#define RGBLIGHT_SLEEP
#define RGBLIGHT_DEFAULT_HUE 230
#define RGBLIGHT_DEFAULT_SAT 230
#define RGBLIGHT_DEFAULT_VAL 179
