#pragma once

#undef RGBLED_NUM
#define TAPPING_TOGGLE 2
#define RGBLED_NUM 12
#define RGBLIGHT_SLEEP
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_DEFAULT_HUE 180
#define RGBLIGHT_DEFAULT_SAT 200
#define RGBLIGHT_DEFAULT_VAL 100
